# Generated by Django 4.1.4 on 2022-12-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Peoples',
        ),
    ]
